import { useState } from "react";
import type { LoaderFunctionArgs } from "@remix-run/node";
import { useOutletContext } from "@remix-run/react";
import {
  BlockStack,
  Box,
  Button,
  Card,
  InlineGrid,
  InlineStack,
  Text,
  TextField,
} from "@shopify/polaris";

import { authenticate } from "../shopify.server";
import AppLayout from "../components/AppLayout";
import type { AppOutletContext } from "./app";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  await authenticate.admin(request);
  return null;
};

export default function ConnectStores() {
  const { shop, plan } = useOutletContext<AppOutletContext>();
  const [code, setCode] = useState("");

  return (
    <AppLayout shop={shop} plan={plan}>
      <BlockStack gap="500">
        <BlockStack gap="100">
          <Text as="h1" variant="headingXl" fontWeight="bold">
            Connect Stores
          </Text>
          <Text as="p" tone="subdued">
            Link this store with another Shopify store to sync products and
            inventory. Connect in under 60 seconds.
          </Text>
        </BlockStack>

        <InlineGrid columns={{ xs: 1, md: 2 }} gap="400">
          {/* Panel 1 — Generate (primary store) */}
          <Card>
            <BlockStack gap="400">
              <BlockStack gap="100">
                <Text as="h2" variant="headingMd">
                  Generate a link code
                </Text>
                <Text as="p" tone="subdued">
                  Use this store as the primary (billing) store. Share the code
                  with the store you want to connect.
                </Text>
              </BlockStack>

              <Box
                background="bg-surface-secondary"
                borderRadius="300"
                padding="500"
              >
                <InlineStack align="center">
                  <Text as="p" variant="heading2xl" fontWeight="bold" tone="subdued">
                    – – – – – –
                  </Text>
                </InlineStack>
              </Box>

              <Button variant="primary" size="large" disabled>
                Generate Code
              </Button>
            </BlockStack>
          </Card>

          {/* Panel 2 — Enter (secondary store) */}
          <Card>
            <BlockStack gap="400">
              <BlockStack gap="100">
                <Text as="h2" variant="headingMd">
                  Enter a link code
                </Text>
                <Text as="p" tone="subdued">
                  Use this store as a secondary store. Enter the 6-digit code
                  generated by the primary store.
                </Text>
              </BlockStack>

              <TextField
                label="Link code"
                labelHidden
                value={code}
                onChange={setCode}
                autoComplete="off"
                maxLength={6}
                placeholder="Enter 6-digit code"
                inputMode="numeric"
              />

              <Button size="large" disabled={code.length !== 6}>
                Connect
              </Button>
            </BlockStack>
          </Card>
        </InlineGrid>
      </BlockStack>
    </AppLayout>
  );
}
